//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salimgareevalanguage
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.ClientService = new HashSet<ClientService>();
            this.Tag = new HashSet<Tag>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public string GenderCode { get; set; }

        public string GenderString
        {
            get
            {
                return Gender.Name;
            }
        }

        public int CountOfSessions
        {
            get
            {
                return SalimgareevaLanguageEntities.GetContext().ClientService.Where(p => p.ClientID == this.ID).Count();
            }
        }

        public string LastSession
        {
            get
            {
                var allsessions = SalimgareevaLanguageEntities.GetContext().ClientService.Where(p => p.ClientID == this.ID);
                DateTime temp = DateTime.MinValue;
                if (allsessions.Count() > 0)
                {
                    foreach (ClientService cs in allsessions)
                    {
                        if (cs.StartTime > temp)
                            temp = cs.StartTime;
                    }
                }
                else
                    return "Нет посещений";
                return temp.ToString("d");
            }
        }

        public DateTime LastSessionDate
        {
            get
            {
                if (this.LastSession == "Нет посещений")
                    return DateTime.MinValue;
                return Convert.ToDateTime( this.LastSession);
            }
        }

        public string Phone { get; set; }
        public string PhotoPath { get; set; }
        public System.DateTime Birthday { get; set; }

        public string BirthdayDate
        {
            get
            {
                return Birthday.ToString("d");
            }
        }
        public string Email { get; set; }
        public System.DateTime RegistrationDate { get; set; }

        public string RegistrationDateStr
        {
            get
            {
                return RegistrationDate.ToString("d");
            }
        }


        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientService> ClientService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tag> Tag { get; set; }
    }
}
